const { chromium } = require('playwright');
const fs = require('fs');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({headless:true});
  const issues=[];
  const out='qa-screenshots';fs.mkdirSync(out,{recursive:true});
  for(const test of [{name:'desktop',width:1440,height:900},{name:'tablet',width:820,height:1100},{name:'mobile',width:390,height:844}]){
    const page=await browser.newPage({viewport:{width:test.width,height:test.height},deviceScaleFactor:1});
    page.on('pageerror',e=>issues.push(test.name+': error JS: '+e.message));
    await page.goto('http://127.0.0.1:8765/',{waitUntil:'load'});
    await page.locator('#week .day-button').first().waitFor();
    assert.equal(await page.locator('#week .day-button').count(),5,test.name+': días');
    assert.equal(await page.locator('#week .week-kcal-ring').count(),5,'Cinco anillos');
    assert.equal(await page.locator('#week .week-meal-row').count(),17,'Ingestas existentes');
    const monday=page.locator('#week .day-button').first();
    assert.match(await monday.innerText(),/Café con leche/);
    const textMonday=await monday.innerText();assert.ok(textMonday.indexOf('Carpaccio')<textMonday.indexOf('Puerros con mayonesa')&&textMonday.indexOf('Puerros con mayonesa')<textMonday.indexOf('Bowl de yogur'),'Orden de cena');
    assert.match(await monday.innerText(),/Ciruelas/);
    assert.ok(!(await monday.innerText()).includes('Incapto'),'Nombre de café simplificado');
    assert.ok(!(await monday.innerText()).includes('Cena lunes'),'Cena sin prefijo técnico');
    assert.equal(await monday.locator('.week-kcal-ring strong').innerText(),'1488');
    assert.equal(await monday.locator('.week-kcal-ring').getAttribute('aria-label'),'1488 kcal registradas de 1600 kcal objetivo');
    assert.equal(await monday.locator('.week-meal-label').count(),4,'iconos de cuatro ingestas');
    assert.equal(await monday.locator('.week-meal-main').count(),2,'comida y cena con jerarquía igual');
    assert.equal(await monday.locator('.week-meal-secondary').count(),2,'desayuno y postre secundarios');
    const friday=page.locator('#week .day-button').last();
    assert.equal(await friday.locator('.week-meal-free').count(),1,'viernes noche libre destacada');
    assert.match(await friday.innerText(),/Noche libre/);
    assert.equal(await friday.locator('.week-meal-row').count(),3,'sin postre oculto');


    assert.equal(await page.locator('#month').inputValue(),'10',test.name+': mes');
    assert.match(await page.locator('#week').innerText(),/Bacalao a la vizcaína con patatas panadera/);
    const scroll=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
    assert.ok(scroll<=2,test.name+': desbordamiento horizontal '+scroll);
    const gallery=page.locator('#batch .batch-gallery');
    assert.equal(await gallery.count(),1,'Batch cooking como galería');
    assert.ok(await gallery.locator('.batch-tile').count()>=2,'Bacalao y otras preparaciones');
    assert.equal(await gallery.locator('a[href$="/recetas/bacalao-a-la-vizcaina/"]').count(),1,'Bacalao aparece en batch cooking');
    assert.equal(await page.locator('#batch .batch-gallery img').count(),await gallery.locator('.batch-tile').count(),'Miniaturas por preparación');
    const tileCount=await gallery.locator('.batch-tile').count();
    assert.ok(await gallery.evaluate(el=>el.classList.contains('batch-cols-'+(el.children.length===1?1:el.children.length===2||el.children.length===4?2:3))),'Columnas de galería correctas');
    await page.screenshot({path:out+'/semana-'+test.name+'.png',fullPage:true});
    await page.getByRole('button',{name:'Ver resumen de Lunes'}).click();
    assert.equal(await page.locator('#day-modal').isVisible(),true);
    assert.match(await page.locator('#quick-content').innerText(),/Patatas panadera/);
    const dialog=await page.locator('#day-dialog').boundingBox();
    assert.ok(dialog.x>=-1&&dialog.x+dialog.width<=test.width+1,test.name+': panel fuera de ventana');
    await page.screenshot({path:out+'/panel-'+test.name+'.png'});
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('#day-modal').isVisible(),false,'Escape');
    await page.getByRole('button',{name:'Ver resumen de Martes'}).click();
    assert.match(await page.locator('#quick-content').innerText(),/Boniato al horno/);
    await page.getByRole('link',{name:/Ver día completo/}).click();
    await page.waitForURL(/\/menus\/10-1\/martes\//);
    await page.locator('.daily-meal').first().waitFor();
    assert.match(await page.locator('body').innerText(),/Carrilleras al vino con boniato al horno/);
    const principal=page.locator('.culinary-group').filter({hasText:'Carrilleras de cerdo al vino'}).first();
    assert.equal(await principal.getAttribute('open'),'','Preparación principal inicialmente visible');
    assert.ok(await principal.locator('a[href*="/recetas/"]').count()>0,'Ficha de receta enlazada');
    const group=page.locator('.culinary-group').filter({hasText:'Boniato al horno'}).first();
    await group.locator('summary').click();
    assert.equal(await group.getAttribute('open'),'');
    assert.match(await group.innerText(),/Boniato/);
    const dailyOverflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);
    assert.ok(dailyOverflow<=2,test.name+': página diaria desborda '+dailyOverflow);
    await page.screenshot({path:out+'/dia-'+test.name+'.png',fullPage:true});
    await page.goto('http://127.0.0.1:8765/recetario/');
    await page.locator('#recipe-catalog').waitFor();
    assert.ok(await page.locator('#recipe-catalog .recipe-tile').count()>=10,'10 recetas iniciales');
    await page.screenshot({path:out+'/recetario-'+test.name+'.png',fullPage:true});
    await page.close();
  }
  await browser.close();
  if(issues.length)throw new Error(issues.join('\n'));
  console.log('PASS: Navegación y estructura en desktop/tablet/mobile; 12 capturas creadas.');
})().catch(e=>{console.error(e);process.exit(1)});
